import { getCached, setCache } from '../../_cache';

// Geopolitical Risk Score 0-10 (10 = highest risk)
// Based on synthesis of public indices: GPR (Caldara/Iacoviello),
// Fragile States Index, Global Peace Index, current conflict status.
// Updated quarterly by maintainer.
const GEO_RISK = [
  { iso3: 'UKR', country: 'Ukraine',           score: 9.8, factors: ['Active war', 'Russia conflict'] },
  { iso3: 'RUS', country: 'Russia',            score: 9.4, factors: ['War', 'Sanctions', 'Isolation'] },
  { iso3: 'PSE', country: 'Palestine',         score: 9.6, factors: ['Active conflict', 'Humanitarian crisis'] },
  { iso3: 'ISR', country: 'Israel',            score: 8.4, factors: ['Active conflict', 'Regional tensions'] },
  { iso3: 'SYR', country: 'Syria',             score: 8.7, factors: ['Civil unrest', 'Power vacuum'] },
  { iso3: 'YEM', country: 'Yemen',             score: 9.0, factors: ['Civil war', 'Famine'] },
  { iso3: 'SDN', country: 'Sudan',             score: 9.2, factors: ['Civil war', 'Humanitarian crisis'] },
  { iso3: 'IRN', country: 'Iran',              score: 8.6, factors: ['Sanctions', 'Proxy conflicts', 'Nuclear'] },
  { iso3: 'PRK', country: 'North Korea',       score: 8.8, factors: ['Nuclear', 'Sanctions', 'Isolation'] },
  { iso3: 'AFG', country: 'Afghanistan',       score: 8.9, factors: ['Taliban rule', 'Humanitarian'] },
  { iso3: 'MMR', country: 'Myanmar',           score: 8.3, factors: ['Civil war', 'Junta'] },
  { iso3: 'LBN', country: 'Lebanon',           score: 7.9, factors: ['Currency collapse', 'Conflict spillover'] },
  { iso3: 'VEN', country: 'Venezuela',         score: 7.8, factors: ['Economic collapse', 'Sanctions'] },
  { iso3: 'HTI', country: 'Haiti',             score: 8.1, factors: ['Gang violence', 'State collapse'] },
  { iso3: 'LBY', country: 'Libya',             score: 7.6, factors: ['Civil unrest', 'Divided governance'] },
  { iso3: 'IRQ', country: 'Iraq',              score: 6.9, factors: ['Insurgency', 'Sectarian tensions'] },
  { iso3: 'PAK', country: 'Pakistan',          score: 7.2, factors: ['Political instability', 'Terrorism'] },
  { iso3: 'NGA', country: 'Nigeria',           score: 6.6, factors: ['Insurgency', 'Banditry'] },
  { iso3: 'COD', country: 'DR Congo',          score: 7.8, factors: ['Armed conflict', 'Resource curse'] },
  { iso3: 'SOM', country: 'Somalia',           score: 8.4, factors: ['Insurgency', 'Famine'] },
  { iso3: 'ETH', country: 'Ethiopia',          score: 7.0, factors: ['Civil tensions', 'Regional conflict'] },
  { iso3: 'CHN', country: 'China',             score: 6.4, factors: ['Taiwan tensions', 'Trade frictions'] },
  { iso3: 'TWN', country: 'Taiwan',            score: 6.8, factors: ['Cross-strait tensions'] },
  { iso3: 'TUR', country: 'Turkey',            score: 5.8, factors: ['Regional friction', 'Currency'] },
  { iso3: 'EGY', country: 'Egypt',             score: 5.5, factors: ['Spillover risk', 'Economic strain'] },
  { iso3: 'BLR', country: 'Belarus',           score: 7.3, factors: ['Russia alignment', 'Sanctions'] },
  { iso3: 'COL', country: 'Colombia',          score: 5.4, factors: ['Insurgency residue', 'Cartels'] },
  { iso3: 'MEX', country: 'Mexico',            score: 5.8, factors: ['Cartel violence'] },
  { iso3: 'IND', country: 'India',             score: 4.4, factors: ['Border tensions'] },
  { iso3: 'KOR', country: 'South Korea',       score: 4.6, factors: ['DPRK threat'] },
  { iso3: 'JPN', country: 'Japan',             score: 3.0, factors: ['Regional tensions'] },
  { iso3: 'USA', country: 'United States',     score: 4.2, factors: ['Polarization', 'Strategic competition'] },
  { iso3: 'GBR', country: 'United Kingdom',    score: 3.4, factors: ['Brexit aftermath'] },
  { iso3: 'FRA', country: 'France',            score: 3.6, factors: ['Civil unrest'] },
  { iso3: 'DEU', country: 'Germany',           score: 3.0, factors: ['Energy security'] },
  { iso3: 'ESP', country: 'Spain',             score: 3.0, factors: [] },
  { iso3: 'ITA', country: 'Italy',             score: 3.2, factors: [] },
  { iso3: 'POL', country: 'Poland',            score: 4.6, factors: ['Frontline NATO', 'Refugees'] },
  { iso3: 'ROU', country: 'Romania',           score: 4.4, factors: ['NATO frontline'] },
  { iso3: 'FIN', country: 'Finland',           score: 4.2, factors: ['Russia border'] },
  { iso3: 'SWE', country: 'Sweden',            score: 3.4, factors: ['NATO'] },
  { iso3: 'NOR', country: 'Norway',            score: 2.8, factors: [] },
  { iso3: 'CAN', country: 'Canada',            score: 2.6, factors: [] },
  { iso3: 'AUS', country: 'Australia',         score: 2.6, factors: ['Indo-Pacific tensions'] },
  { iso3: 'NZL', country: 'New Zealand',       score: 2.0, factors: [] },
  { iso3: 'SGP', country: 'Singapore',         score: 2.6, factors: [] },
  { iso3: 'CHE', country: 'Switzerland',       score: 2.0, factors: [] },
  { iso3: 'NLD', country: 'Netherlands',       score: 2.8, factors: [] },
  { iso3: 'BEL', country: 'Belgium',           score: 3.0, factors: [] },
  { iso3: 'AUT', country: 'Austria',           score: 2.8, factors: [] },
  { iso3: 'IRL', country: 'Ireland',           score: 2.4, factors: [] },
  { iso3: 'PRT', country: 'Portugal',          score: 2.4, factors: [] },
  { iso3: 'GRC', country: 'Greece',            score: 3.6, factors: ['Turkey tensions'] },
  { iso3: 'CYP', country: 'Cyprus',            score: 4.0, factors: ['Division'] },
  { iso3: 'BRA', country: 'Brazil',            score: 4.2, factors: ['Political polarization'] },
  { iso3: 'ARG', country: 'Argentina',         score: 5.4, factors: ['Currency', 'Inflation'] },
  { iso3: 'CHL', country: 'Chile',             score: 3.0, factors: [] },
  { iso3: 'PER', country: 'Peru',              score: 4.6, factors: ['Political instability'] },
  { iso3: 'ECU', country: 'Ecuador',           score: 6.2, factors: ['Cartel violence'] },
  { iso3: 'BOL', country: 'Bolivia',           score: 4.8, factors: ['Political tension'] },
  { iso3: 'CUB', country: 'Cuba',              score: 6.4, factors: ['Sanctions', 'Economic crisis'] },
  { iso3: 'NIC', country: 'Nicaragua',         score: 5.6, factors: ['Authoritarian'] },
  { iso3: 'SAU', country: 'Saudi Arabia',      score: 4.6, factors: ['Yemen war', 'Regional rival Iran'] },
  { iso3: 'ARE', country: 'UAE',               score: 3.2, factors: [] },
  { iso3: 'QAT', country: 'Qatar',             score: 3.4, factors: [] },
  { iso3: 'KWT', country: 'Kuwait',            score: 3.2, factors: [] },
  { iso3: 'JOR', country: 'Jordan',            score: 5.6, factors: ['Regional spillover'] },
  { iso3: 'BHR', country: 'Bahrain',           score: 4.6, factors: ['Regional tensions'] },
  { iso3: 'KAZ', country: 'Kazakhstan',        score: 5.0, factors: ['Russia neighbor'] },
  { iso3: 'UZB', country: 'Uzbekistan',        score: 4.6, factors: [] },
  { iso3: 'AZE', country: 'Azerbaijan',        score: 5.4, factors: ['Armenia conflict'] },
  { iso3: 'ARM', country: 'Armenia',           score: 6.2, factors: ['Azerbaijan war'] },
  { iso3: 'GEO', country: 'Georgia',           score: 5.4, factors: ['Russia tensions'] },
  { iso3: 'MNG', country: 'Mongolia',          score: 3.4, factors: [] },
  { iso3: 'IDN', country: 'Indonesia',         score: 3.6, factors: [] },
  { iso3: 'THA', country: 'Thailand',          score: 4.4, factors: ['Political instability'] },
  { iso3: 'MYS', country: 'Malaysia',          score: 3.4, factors: [] },
  { iso3: 'PHL', country: 'Philippines',       score: 4.6, factors: ['South China Sea'] },
  { iso3: 'VNM', country: 'Vietnam',           score: 3.4, factors: ['South China Sea'] },
  { iso3: 'BGD', country: 'Bangladesh',        score: 5.2, factors: ['Political unrest'] },
  { iso3: 'LKA', country: 'Sri Lanka',         score: 5.4, factors: ['Economic crisis'] },
  { iso3: 'NPL', country: 'Nepal',             score: 4.4, factors: [] },
  { iso3: 'KEN', country: 'Kenya',             score: 4.8, factors: [] },
  { iso3: 'ZAF', country: 'South Africa',      score: 5.0, factors: ['Civil tensions', 'Economic strain'] },
  { iso3: 'GHA', country: 'Ghana',             score: 4.0, factors: [] },
  { iso3: 'MAR', country: 'Morocco',           score: 3.8, factors: [] },
  { iso3: 'TUN', country: 'Tunisia',           score: 5.4, factors: ['Political instability'] },
  { iso3: 'DZA', country: 'Algeria',           score: 5.6, factors: [] },
];

// Proven oil reserves (Bbbl) — BP Statistical Review approximations
const OIL_RESERVES = [
  { iso3: 'VEN', country: 'Venezuela',     reserves: 303 },
  { iso3: 'SAU', country: 'Saudi Arabia',  reserves: 267 },
  { iso3: 'IRN', country: 'Iran',          reserves: 209 },
  { iso3: 'CAN', country: 'Canada',        reserves: 170 },
  { iso3: 'IRQ', country: 'Iraq',          reserves: 145 },
  { iso3: 'KWT', country: 'Kuwait',        reserves: 102 },
  { iso3: 'ARE', country: 'UAE',           reserves: 111 },
  { iso3: 'RUS', country: 'Russia',        reserves: 108 },
  { iso3: 'LBY', country: 'Libya',         reserves:  48 },
  { iso3: 'NGA', country: 'Nigeria',       reserves:  37 },
  { iso3: 'USA', country: 'United States', reserves:  47 },
  { iso3: 'KAZ', country: 'Kazakhstan',    reserves:  30 },
  { iso3: 'CHN', country: 'China',         reserves:  26 },
  { iso3: 'QAT', country: 'Qatar',         reserves:  25 },
  { iso3: 'BRA', country: 'Brazil',        reserves:  13 },
  { iso3: 'ALG', country: 'Algeria',       reserves:  12 },
  { iso3: 'NOR', country: 'Norway',        reserves:   8 },
  { iso3: 'AGO', country: 'Angola',        reserves:   8 },
  { iso3: 'MEX', country: 'Mexico',        reserves:   6 },
  { iso3: 'OMN', country: 'Oman',          reserves:   5 },
  { iso3: 'IND', country: 'India',         reserves:   4.5 },
  { iso3: 'GBR', country: 'United Kingdom', reserves:  2.5 },
  { iso3: 'IDN', country: 'Indonesia',     reserves:   2.4 },
  { iso3: 'COL', country: 'Colombia',      reserves:   2.0 },
  { iso3: 'MYS', country: 'Malaysia',      reserves:   2.7 },
  { iso3: 'EGY', country: 'Egypt',         reserves:   3.3 },
  { iso3: 'AUS', country: 'Australia',     reserves:   2.4 },
  { iso3: 'ARG', country: 'Argentina',     reserves:   2.4 },
  { iso3: 'YEM', country: 'Yemen',         reserves:   3.0 },
  { iso3: 'AZE', country: 'Azerbaijan',    reserves:   7.0 },
];

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const view = searchParams.get('view') || 'risk';

  if (view === 'oil') {
    return Response.json({ kind: 'oil', data: OIL_RESERVES, lastUpdated: new Date().toISOString() });
  }

  return Response.json({ kind: 'risk', data: GEO_RISK, lastUpdated: new Date().toISOString() });
}